"""Conformance-harness pytest configuration for python-docx.

Discovers the fixture source the byte-round-trip harness runs against:

- Every ``*.office.docx`` file under the reference-corpus directory at
  ``~/code/ooxml-reference-corpus/fixtures/docx/``. Path is overridable
  with the ``DOCX_CORPUS_ROOT`` env var. When the directory is missing
  the conformance tests skip cleanly — the ``.office.docx`` fixture
  set is authored by the user via Microsoft Word desktop and may not
  exist in every checkout.

Plain ``*.docx`` fixtures generated by python-docx or scripts
(everything in the corpus that *doesn't* end in ``.office.docx``) are
deliberately excluded. Those are synthesised by the same writer under
test — byte-identical round-trip against those only exercises
``writer → writer`` determinism, which ``test_reproducible_save.py``
already covers. The ``.office.docx`` variants come from Microsoft
Word itself and exercise ``reader → writer`` fidelity, which is the
contract this harness enforces.

The list is computed **at import time** so pytest's parametrisation
machinery can build per-fixture test IDs that are visible in verbose
output (e.g. ``test_round_trip_is_byte_identical[bold-text.office.docx]``).
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

import pytest

__all__ = [
    "CORPUS_FIXTURES",
    "CORPUS_FIXTURE_IDS",
    "ALL_FIXTURES",
    "ALL_FIXTURE_IDS",
    "discover_corpus_fixtures",
]


# -- Only Office-authored fixtures participate in the byte-round-trip
# -- contract. Generator-authored ``*.docx`` fixtures are synthesised
# -- by this same writer and so don't exercise the ``reader → writer``
# -- fidelity path; they are excluded by filename suffix.
_OFFICE_DOCX_SUFFIX = ".office.docx"


def _corpus_root() -> Path:
    """Return the resolved corpus-fixture directory.

    Mirrors the unit-conftest lookup convention but kept as a private
    copy so this module stays independently importable outside a
    pytest session.
    """
    override = os.environ.get("DOCX_CORPUS_ROOT")
    if override:
        return Path(override).expanduser().resolve()
    return Path("~/code/ooxml-reference-corpus/fixtures/docx").expanduser()


def discover_corpus_fixtures(root: Optional[Path] = None) -> list[Path]:
    """Return every Office-authored ``.office.docx`` fixture under ``root``.

    Sorted by filename so parametrisation is deterministic across runs.
    Returns an empty list when the directory is absent — the caller is
    expected to guard with a module-level skipif or per-test skip so
    the harness doesn't raise on clean checkouts.
    """
    base = root or _corpus_root()
    if not base.is_dir():
        return []
    return sorted(
        path
        for path in base.iterdir()
        if path.is_file()
        and path.name.lower().endswith(_OFFICE_DOCX_SUFFIX)
        # Skip MS Office lock files (``~$bold-text.office.docx``) — they
        # mean Word desktop is *currently editing* the fixture and the
        # lock is a tiny OLE CFB blob, not a zip.
        and not path.name.startswith("~$")
    )


CORPUS_FIXTURES: list[Path] = discover_corpus_fixtures()
CORPUS_FIXTURE_IDS: list[str] = [p.name for p in CORPUS_FIXTURES]

ALL_FIXTURES: list[Path] = list(CORPUS_FIXTURES)
ALL_FIXTURE_IDS: list[str] = list(CORPUS_FIXTURE_IDS)


@pytest.fixture(scope="session")
def corpus_fixtures_list() -> list[Path]:
    """Expose the discovered corpus fixture list as a session fixture."""
    return list(CORPUS_FIXTURES)
