[tox]
envlist = py39, py310, py311, py312, py313

[testenv]
deps =
    behave>=1.2.6
    pyparsing>=3.2.3
    pytest>=8.4.0
    ruff>=0.11.13

commands =
    py.test -qx
    behave --format progress --stop --tags=-wip
