"""Contract / NDA template family — opinionated authoring helpers.

Closes #62.

This module exposes four template factories that build entire
boilerplate-laden contract documents in one call::

    from docx.kit.contracts import (
        nda,
        msa,
        sow,
        contractor_agreement,
    )

    doc = nda(
        kind="mutual",
        parties=[
            {"name": "Acme Corp", "address": "123 Pitt St, Sydney NSW 2000"},
            {"name": "Beta Inc",  "address": "1 Market St, San Francisco CA"},
        ],
        effective_date="2026-03-01",
        term_years=3,
        governing_law="New South Wales, Australia",
    )
    doc.save("acme-beta-nda.docx")

The four factories — :func:`nda`, :func:`msa`, :func:`sow`,
:func:`contractor_agreement` — each return a fresh |Document| pre-populated
with the conventional sections of the matching contract type. The shapes
follow common Australian commercial-law starting points (Australian
Consumer Law-aware, NSW governing-law defaults, GST-inclusive payment
language) so a small NSW-based business can use the output as the *first
draft* of a real agreement without re-typing boilerplate every time.

.. warning::

    **Not legal advice.** Every document returned by this module is
    boilerplate intended as a *starting point only*. The text has not
    been reviewed by a lawyer, makes assumptions about jurisdiction,
    party type, and tax treatment that may not fit a given engagement,
    and elides clauses (insurance, modern-slavery, privacy, IP
    assignment carve-outs, change-control, dispute-escalation,
    indemnity caps tied to specific risk classes, …) that are commonly
    required in real-world contracts. Use the output as a structural
    skeleton only and have a lawyer review every word before signing.
    The authors of python-docx accept no responsibility for losses
    arising from reliance on this boilerplate.

Common conventions across the four factories:

- **Title page** — centred title, parties block, effective-date line.
- **Numbered headings** — ``Heading 1`` style for the top-level
  numbered clauses (``1.``, ``2.``, …). Sub-clauses are rendered as
  indented paragraphs starting ``1.1`` / ``1.2`` so the document tree
  stays flat (Word will renumber on field-update if the caller swaps
  the headings to a numbered style).
- **Signature block** — last page carries a signature table for each
  party with name / title / date placeholders.
- **AUS defaults** — ``governing_law`` defaults to "New South Wales,
  Australia"; the MSA payment clause references "Australian dollars
  (AUD)" and "GST exclusive unless stated otherwise"; consumer
  guarantees under the Australian Consumer Law are explicitly preserved
  in the warranties / liability clauses where required by statute.
- **No XML reach-down** — the kit composes only public python-docx API
  (``Document.add_paragraph``, ``Document.add_heading``,
  ``Document.add_page_break``, ``Document.add_table``,
  ``Document.add_section``).

.. versionadded:: 2026.05.29
"""

from __future__ import annotations

from typing import TYPE_CHECKING, List, Mapping, Optional, Sequence, Union

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

if TYPE_CHECKING:
    from docx.document import Document as DocumentCls
    from docx.text.paragraph import Paragraph


# -- Default values used across the four factories. NSW / AUS biased. --
_DEFAULT_GOVERNING_LAW = "New South Wales, Australia"
_DEFAULT_TERM_YEARS = 3
_DEFAULT_PAYMENT_TERMS = "Net 30"
_DEFAULT_CURRENCY = "AUD"

# -- Standard "not legal advice" disclaimer rendered verbatim into every
# -- generated document so a downstream user opening the file in Word
# -- sees the same caveat the docstring above carries. --
_DISCLAIMER = (
    "DISCLAIMER: This document is template boilerplate generated by "
    "python-docx. It is not legal advice and has not been reviewed by "
    "a lawyer. Use as a starting point only and have qualified legal "
    "counsel review every clause before signing."
)


# -- Helpers --------------------------------------------------------------


def _format_party_label(party: Mapping[str, str]) -> str:
    """Return ``"Acme Corp of 123 Pitt St"`` from a party dict.

    A party dict has at minimum a ``name`` key; ``address`` is optional
    but conventional. The "of" connector matches AUS contract drafting
    house style.
    """
    name = party.get("name", "").strip()
    if not name:
        raise ValueError("each party requires a non-empty 'name'")
    address = party.get("address", "").strip()
    if address:
        return f"{name} of {address}"
    return name


def _add_disclaimer(document: DocumentCls) -> Paragraph:
    """Append the standard "not legal advice" notice to ``document``."""
    para = document.add_paragraph()
    run = para.add_run(_DISCLAIMER)
    run.italic = True
    run.bold = True
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    return para


def _add_title(document: DocumentCls, title: str) -> Paragraph:
    """Append a centred document title in the ``Title`` style (or fallback)."""
    style = "Title"
    try:
        document.styles[style]
    except KeyError:
        style = "Normal"
    para = document.add_paragraph(title, style=style)
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    return para


def _add_clause(
    document: DocumentCls,
    number: int,
    heading: str,
    body: Union[str, Sequence[str]],
) -> List[Paragraph]:
    """Append a numbered top-level clause and return its paragraphs.

    Renders ``"{number}. {heading}"`` as a ``Heading 1``-styled
    paragraph followed by one paragraph per item in ``body`` (a string
    is treated as a single paragraph; a sequence emits one per item).
    """
    paragraphs: List[Paragraph] = []
    paragraphs.append(
        document.add_heading(f"{number}. {heading}", level=1)
    )
    if isinstance(body, str):
        chunks: Sequence[str] = [body]
    else:
        chunks = list(body)
    for chunk in chunks:
        if not chunk:
            continue
        paragraphs.append(document.add_paragraph(chunk))
    return paragraphs


def _add_subclause(
    document: DocumentCls, number: str, text: str
) -> Paragraph:
    """Append an indented sub-clause paragraph (e.g. ``"1.2 Foo bar."``)."""
    para = document.add_paragraph(f"{number} {text}")
    para.paragraph_format.left_indent = None  # use style indent
    return para


def _add_parties_block(
    document: DocumentCls,
    parties: Sequence[Mapping[str, str]],
) -> List[Paragraph]:
    """Append a ``BETWEEN`` / parties identification block.

    Renders the conventional AUS contract opener::

        BETWEEN:
        (1) Acme Corp of 123 Pitt St, Sydney NSW 2000 ("Party 1"); and
        (2) Beta Inc of 1 Market St, San Francisco CA ("Party 2").
    """
    paragraphs: List[Paragraph] = []
    paragraphs.append(document.add_paragraph("BETWEEN:"))
    last = len(parties) - 1
    for index, party in enumerate(parties):
        label = _format_party_label(party)
        terminator = "." if index == last else "; and"
        text = f"({index + 1}) {label} (\"Party {index + 1}\"){terminator}"
        paragraphs.append(document.add_paragraph(text))
    return paragraphs


def _add_signature_block(
    document: DocumentCls,
    parties: Sequence[Mapping[str, str]],
) -> List[Paragraph]:
    """Append a signature block — heading + one signature stub per party.

    Returns the heading paragraph plus the per-party label paragraphs
    (the underline placeholders are runs inside those paragraphs, not
    standalone paragraphs).
    """
    paragraphs: List[Paragraph] = []
    paragraphs.append(document.add_heading("Signed", level=1))
    for index, party in enumerate(parties):
        name = party.get("name", f"Party {index + 1}")
        paragraphs.append(
            document.add_paragraph(
                f"Signed for and on behalf of {name}:"
            )
        )
        # -- underline placeholders for handwritten name / title / date --
        signature_line = document.add_paragraph(
            "Name: ______________________________"
        )
        paragraphs.append(signature_line)
        title_line = document.add_paragraph(
            "Title: ______________________________"
        )
        paragraphs.append(title_line)
        date_line = document.add_paragraph(
            "Date: ______________________________"
        )
        paragraphs.append(date_line)
        paragraphs.append(document.add_paragraph(""))  # gap
    return paragraphs


def _validate_parties(parties: Sequence[Mapping[str, str]]) -> None:
    """Raise :class:`ValueError` when ``parties`` is malformed.

    The expectation is a sequence of length >= 2 where every item is a
    mapping that includes a non-empty ``name``. A length-1 sequence is
    rejected because every contract template here is a *bilateral*
    instrument by definition.
    """
    if not parties or len(parties) < 2:
        raise ValueError(
            "parties must contain at least two parties; got %d"
            % (len(parties) if parties else 0)
        )
    for index, party in enumerate(parties):
        if not isinstance(party, Mapping):  # type: ignore[arg-type]
            raise ValueError(
                "parties[%d] must be a mapping with a 'name' key" % index
            )
        if not party.get("name"):
            raise ValueError(
                "parties[%d] is missing a non-empty 'name'" % index
            )


# -- NDA ------------------------------------------------------------------


def nda(
    kind: str = "mutual",
    parties: Optional[Sequence[Mapping[str, str]]] = None,
    effective_date: Optional[str] = None,
    term_years: int = _DEFAULT_TERM_YEARS,
    governing_law: str = _DEFAULT_GOVERNING_LAW,
) -> DocumentCls:
    """Build a Non-Disclosure Agreement and return the |Document|.

    Generates a complete NDA with the standard sections: definitions,
    mutual obligations, term, return of materials, remedies, and
    governing law. ``kind`` selects between ``"mutual"`` (both parties
    disclose and receive) and ``"one-way"`` (Party 1 discloses, Party 2
    receives only) — the default is ``"mutual"`` because mutual NDAs
    are the more common shape between commercial counterparts.

    Parameters
    ----------
    kind
        ``"mutual"`` (default) or ``"one-way"``. Determines whether the
        confidentiality obligations apply to both parties or only the
        recipient.
    parties
        Sequence of party dicts, each with ``name`` (required) and
        ``address`` (optional). At least two parties are required.
    effective_date
        ISO date string (``"2026-03-01"``) rendered verbatim. ``None``
        leaves the effective-date placeholder.
    term_years
        Length of the confidentiality obligation in years. Defaults to
        3 — a common commercial baseline. Pass 0 to render
        "indefinitely" instead of an integer.
    governing_law
        Jurisdiction whose law governs the NDA. Defaults to
        ``"New South Wales, Australia"``.

    Returns
    -------
    Document
        The freshly-built |Document|. Save with :meth:`Document.save`.

    Raises
    ------
    ValueError
        When ``kind`` is not one of the two recognised values, when
        ``parties`` is missing or malformed, or when ``term_years`` is
        negative.

    .. warning::
        **Not legal advice.** See the module docstring for the full
        disclaimer. The output is starting-point boilerplate only.

    .. versionadded:: 2026.05.29
    """
    if kind not in ("mutual", "one-way"):
        raise ValueError(
            "kind must be 'mutual' or 'one-way'; got %r" % kind
        )
    if parties is None:
        raise ValueError("parties is required")
    _validate_parties(parties)
    if term_years < 0:
        raise ValueError("term_years must be >= 0; got %d" % term_years)

    document = Document()

    title = (
        "Mutual Non-Disclosure Agreement"
        if kind == "mutual"
        else "One-Way Non-Disclosure Agreement"
    )
    _add_title(document, title)
    _add_disclaimer(document)

    if effective_date:
        date_para = document.add_paragraph(
            f"Effective Date: {effective_date}"
        )
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    _add_parties_block(document, parties)

    # -- recitals --
    document.add_paragraph(
        "WHEREAS the Parties wish to explore a potential business "
        "relationship and may need to disclose confidential information "
        "to one another for that purpose;"
    )
    document.add_paragraph(
        "NOW THEREFORE, in consideration of the mutual covenants "
        "below, the Parties agree as follows:"
    )

    # -- 1. Definitions --
    _add_clause(
        document,
        1,
        "Definitions",
        [
            "\"Confidential Information\" means any non-public information "
            "disclosed by one Party (the \"Disclosing Party\") to the "
            "other Party (the \"Receiving Party\"), in any form, that is "
            "marked confidential, identified as confidential at the time "
            "of disclosure, or that a reasonable person would understand "
            "to be confidential given the nature of the information and "
            "the circumstances of disclosure.",
            "\"Purpose\" means the evaluation, negotiation, or "
            "performance of the potential business relationship between "
            "the Parties.",
        ],
    )

    # -- 2. Obligations --
    if kind == "mutual":
        obligations = (
            "Each Party shall, with respect to the other Party's "
            "Confidential Information: (a) hold it in strict confidence; "
            "(b) use it solely for the Purpose; (c) restrict access to "
            "personnel with a need to know who are bound by "
            "confidentiality obligations no less protective than those "
            "in this Agreement; and (d) take reasonable steps to protect "
            "it from unauthorised use or disclosure."
        )
    else:
        obligations = (
            "The Receiving Party shall, with respect to the Disclosing "
            "Party's Confidential Information: (a) hold it in strict "
            "confidence; (b) use it solely for the Purpose; "
            "(c) restrict access to personnel with a need to know who "
            "are bound by confidentiality obligations no less protective "
            "than those in this Agreement; and (d) take reasonable steps "
            "to protect it from unauthorised use or disclosure."
        )
    _add_clause(document, 2, "Obligations of Confidentiality", obligations)

    # -- 3. Exclusions --
    _add_clause(
        document,
        3,
        "Exclusions",
        "The obligations in clause 2 do not apply to information that: "
        "(a) is or becomes publicly available through no fault of the "
        "Receiving Party; (b) was rightfully known to the Receiving "
        "Party prior to disclosure; (c) is rightfully obtained from a "
        "third party without restriction; or (d) is independently "
        "developed by the Receiving Party without use of the Disclosing "
        "Party's Confidential Information.",
    )

    # -- 4. Term --
    if term_years == 0:
        term_text = (
            "This Agreement commences on the Effective Date and "
            "continues indefinitely until terminated in writing by "
            "mutual agreement."
        )
    else:
        term_text = (
            f"This Agreement commences on the Effective Date and "
            f"continues for a period of {term_years} year"
            f"{'s' if term_years != 1 else ''}, after which the "
            f"obligations of confidentiality survive for a further three "
            f"years with respect to information that constitutes a "
            f"trade secret under applicable law."
        )
    _add_clause(document, 4, "Term", term_text)

    # -- 5. Return of Materials --
    _add_clause(
        document,
        5,
        "Return of Materials",
        "Upon written request by the Disclosing Party, or upon "
        "termination of this Agreement, the Receiving Party shall "
        "promptly return or destroy all Confidential Information in "
        "its possession or control, including all copies, extracts, "
        "and derivative works, and shall certify such return or "
        "destruction in writing if requested.",
    )

    # -- 6. Remedies --
    _add_clause(
        document,
        6,
        "Remedies",
        "The Parties acknowledge that breach of this Agreement may "
        "cause irreparable harm for which monetary damages would be "
        "an inadequate remedy. Accordingly, the non-breaching Party "
        "is entitled to seek equitable relief, including injunction "
        "and specific performance, in addition to all other remedies "
        "available at law or in equity.",
    )

    # -- 7. Governing Law --
    _add_clause(
        document,
        7,
        "Governing Law",
        f"This Agreement is governed by the laws of {governing_law}. "
        f"The Parties submit to the exclusive jurisdiction of the "
        f"courts of {governing_law} in respect of any dispute arising "
        f"out of or in connection with this Agreement.",
    )

    # -- 8. General --
    _add_clause(
        document,
        8,
        "General",
        [
            "This Agreement constitutes the entire agreement between "
            "the Parties with respect to its subject matter and "
            "supersedes all prior or contemporaneous understandings.",
            "No amendment of this Agreement is effective unless in "
            "writing and signed by both Parties.",
            "If any provision of this Agreement is held unenforceable, "
            "the remaining provisions continue in full force and effect.",
        ],
    )

    document.add_page_break()
    _add_signature_block(document, parties)

    return document


# -- MSA ------------------------------------------------------------------


def msa(
    client: Optional[str] = None,
    vendor: Optional[str] = None,
    parties: Optional[Sequence[Mapping[str, str]]] = None,
    effective_date: Optional[str] = None,
    payment_terms: str = _DEFAULT_PAYMENT_TERMS,
    currency: str = _DEFAULT_CURRENCY,
    governing_law: str = _DEFAULT_GOVERNING_LAW,
    liability_cap_multiple: int = 1,
) -> DocumentCls:
    """Build a Master Services Agreement and return the |Document|.

    Generates an MSA with the conventional sections: services framework,
    ordering process (SOWs), payment, intellectual property, warranties,
    liability cap, and termination. The MSA is the *umbrella* contract;
    individual engagements are scoped via SOWs that incorporate this
    agreement by reference (see :func:`sow`).

    Parameters
    ----------
    client
        Convenience: the client party's name. When supplied without
        ``parties``, used to construct ``parties=[{client}, {vendor}]``.
    vendor
        Convenience: the vendor party's name. Pairs with ``client``.
    parties
        Explicit sequence of party dicts (overrides ``client`` /
        ``vendor`` when supplied). Use this form when the parties have
        addresses or there are more than two parties.
    effective_date
        ISO date string rendered verbatim.
    payment_terms
        Net-X invoice terms; defaults to ``"Net 30"``.
    currency
        ISO currency code; defaults to ``"AUD"``. Rendered into the
        payment clause.
    governing_law
        Jurisdiction; defaults to ``"New South Wales, Australia"``.
    liability_cap_multiple
        Liability cap expressed as a multiple of the fees paid in the
        12 months preceding the claim. Defaults to 1 (one-times
        trailing-12-month fees) — the conservative AUS-market default.

    Returns
    -------
    Document
        The freshly-built |Document|.

    Raises
    ------
    ValueError
        When neither ``parties`` nor a ``client`` / ``vendor`` pair is
        supplied, or when the supplied ``parties`` is malformed.

    .. warning::
        **Not legal advice.** See module docstring.

    .. versionadded:: 2026.05.29
    """
    if parties is None:
        if not client or not vendor:
            raise ValueError(
                "supply either 'parties' or both 'client' and 'vendor'"
            )
        parties = [{"name": client}, {"name": vendor}]
    _validate_parties(parties)
    if liability_cap_multiple < 0:
        raise ValueError(
            "liability_cap_multiple must be >= 0; got %d"
            % liability_cap_multiple
        )

    document = Document()
    _add_title(document, "Master Services Agreement")
    _add_disclaimer(document)

    if effective_date:
        date_para = document.add_paragraph(
            f"Effective Date: {effective_date}"
        )
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    _add_parties_block(document, parties)
    document.add_paragraph(
        "The Parties agree on the following framework for the supply "
        "of services from time to time, as described in one or more "
        "Statements of Work entered into under this Agreement."
    )

    # -- 1. Services Framework --
    _add_clause(
        document,
        1,
        "Services Framework",
        "This Agreement establishes the general terms on which the "
        "Vendor (Party 2) may from time to time supply services to the "
        "Client (Party 1). The specific scope, deliverables, "
        "milestones, fees, and acceptance criteria of any engagement "
        "are set out in a Statement of Work (\"SOW\") executed by both "
        "Parties and incorporated into this Agreement by reference.",
    )

    # -- 2. Ordering Process --
    _add_clause(
        document,
        2,
        "Ordering Process",
        [
            "Each engagement under this Agreement is initiated by the "
            "Parties executing a SOW substantially in the form attached "
            "as Schedule A.",
            "In the event of a conflict between this Agreement and a "
            "SOW, this Agreement prevails unless the SOW expressly "
            "states the conflicting term overrides this Agreement and "
            "is signed by both Parties.",
        ],
    )

    # -- 3. Fees and Payment --
    _add_clause(
        document,
        3,
        "Fees and Payment",
        [
            f"All fees are stated in {currency} and are exclusive of "
            f"GST unless expressly stated otherwise. Where GST applies, "
            f"the Vendor will provide a valid tax invoice and the "
            f"Client will pay the GST in addition to the fees.",
            f"Invoices are payable {payment_terms} from the date of a "
            f"valid tax invoice. Undisputed amounts not paid by the due "
            f"date may attract simple interest at the Reserve Bank of "
            f"Australia cash rate plus 2% per annum, calculated daily.",
            "The Client may withhold any portion of an invoice that is "
            "the subject of a good-faith dispute notified in writing to "
            "the Vendor within 14 days of receipt of the invoice.",
        ],
    )

    # -- 4. Intellectual Property --
    _add_clause(
        document,
        4,
        "Intellectual Property",
        [
            "Each Party retains all right, title, and interest in its "
            "pre-existing intellectual property (\"Background IP\").",
            "Subject to payment of all fees due, the Vendor assigns to "
            "the Client all right, title, and interest in any "
            "intellectual property created specifically for the Client "
            "in performance of a SOW (\"Foreground IP\"), excluding the "
            "Vendor's Background IP and any third-party components. The "
            "Vendor grants the Client a perpetual, royalty-free, "
            "non-exclusive licence to use the Vendor's Background IP to "
            "the extent embedded in the Foreground IP.",
        ],
    )

    # -- 5. Warranties --
    _add_clause(
        document,
        5,
        "Warranties",
        [
            "The Vendor warrants that the services will be performed "
            "with due care and skill, by appropriately qualified "
            "personnel, and in a manner consistent with prevailing "
            "industry standards.",
            "Nothing in this Agreement excludes, restricts, or modifies "
            "any guarantee, right, or remedy implied by, or conferred "
            "under, the Australian Consumer Law (Schedule 2 to the "
            "Competition and Consumer Act 2010 (Cth)) or any other "
            "law that cannot lawfully be excluded.",
            "Except as expressly set out in this Agreement, and to the "
            "maximum extent permitted by law, all other warranties, "
            "representations, and conditions, whether express or "
            "implied, are excluded.",
        ],
    )

    # -- 6. Liability --
    if liability_cap_multiple == 0:
        cap_text = (
            "the total fees paid by the Client to the Vendor under the "
            "relevant SOW in the 12 months preceding the event giving "
            "rise to the claim"
        )
    elif liability_cap_multiple == 1:
        cap_text = (
            "the total fees paid by the Client to the Vendor under the "
            "relevant SOW in the 12 months preceding the event giving "
            "rise to the claim"
        )
    else:
        cap_text = (
            f"{liability_cap_multiple} times the total fees paid by the "
            f"Client to the Vendor under the relevant SOW in the "
            f"12 months preceding the event giving rise to the claim"
        )
    _add_clause(
        document,
        6,
        "Liability",
        [
            "Subject to the remainder of this clause, and to the "
            "maximum extent permitted by law, each Party's total "
            f"aggregate liability arising out of or in connection with "
            f"this Agreement, whether in contract, tort (including "
            f"negligence), under statute, or otherwise, is limited to "
            f"{cap_text}.",
            "Neither Party is liable for any indirect, consequential, "
            "special, or punitive damages, or for loss of profit, "
            "revenue, anticipated savings, business opportunity, or "
            "goodwill, however caused.",
            "The limitations in this clause do not apply to liability "
            "for: (a) death or personal injury caused by negligence; "
            "(b) fraud or fraudulent misrepresentation; (c) breach of "
            "confidentiality obligations; (d) infringement of the "
            "other Party's intellectual property; or (e) any liability "
            "that cannot lawfully be limited.",
        ],
    )

    # -- 7. Termination --
    _add_clause(
        document,
        7,
        "Termination",
        [
            "Either Party may terminate this Agreement for convenience "
            "on 60 days' written notice, provided that any SOW in "
            "effect at the date of notice continues in force until "
            "completion or earlier termination of that SOW.",
            "Either Party may terminate this Agreement or any SOW "
            "immediately by written notice if the other Party: "
            "(a) commits a material breach that is not remedied within "
            "30 days of written notice; or (b) becomes insolvent, "
            "enters administration, or otherwise ceases to carry on "
            "business.",
            "Termination does not affect any rights or obligations "
            "accrued before termination, and the clauses that by their "
            "nature should survive termination (including "
            "confidentiality, IP, liability, and governing law) "
            "survive.",
        ],
    )

    # -- 8. Confidentiality --
    _add_clause(
        document,
        8,
        "Confidentiality",
        "Each Party shall keep the other Party's confidential "
        "information confidential and use it only for the purposes of "
        "this Agreement. The obligations in this clause survive "
        "termination for a period of three years.",
    )

    # -- 9. Governing Law --
    _add_clause(
        document,
        9,
        "Governing Law and Jurisdiction",
        f"This Agreement is governed by the laws of {governing_law}. "
        f"The Parties submit to the exclusive jurisdiction of the "
        f"courts of {governing_law} in respect of any dispute arising "
        f"out of or in connection with this Agreement.",
    )

    # -- 10. General --
    _add_clause(
        document,
        10,
        "General",
        [
            "This Agreement, together with any executed SOWs, "
            "constitutes the entire agreement between the Parties.",
            "No amendment is effective unless in writing and signed by "
            "both Parties.",
            "If any provision is held unenforceable, the remaining "
            "provisions continue in full force.",
            "Notices must be in writing and delivered by hand, post, or "
            "email to the address specified in the parties block.",
        ],
    )

    document.add_page_break()
    _add_signature_block(document, parties)

    return document


# -- SOW ------------------------------------------------------------------


def sow(
    parent_msa: Optional[str] = None,
    parties: Optional[Sequence[Mapping[str, str]]] = None,
    client: Optional[str] = None,
    vendor: Optional[str] = None,
    project_name: Optional[str] = None,
    effective_date: Optional[str] = None,
    deliverables: Optional[Sequence[str]] = None,
    milestones: Optional[Sequence[Mapping[str, str]]] = None,
    fees: Optional[str] = None,
    governing_law: str = _DEFAULT_GOVERNING_LAW,
) -> DocumentCls:
    """Build a Statement of Work (SOW) and return the |Document|.

    A SOW is the operational instrument under an MSA: it scopes a
    specific engagement, lists deliverables, schedules milestones, and
    states the fees. This factory produces an SOW that incorporates the
    parent MSA by reference.

    Parameters
    ----------
    parent_msa
        Identifier of the parent MSA (e.g. ``"msa-2026-001"``). Rendered
        in the recital to incorporate by reference. ``None`` produces a
        placeholder line the caller can fill in.
    parties
        Sequence of party dicts (overrides ``client`` / ``vendor``).
    client
        Convenience: the client party's name (paired with ``vendor``).
    vendor
        Convenience: the vendor party's name.
    project_name
        Human-readable name for the engagement (e.g. ``"Mobile App
        Build, Phase 1"``). Rendered in the title.
    effective_date
        ISO date string.
    deliverables
        Sequence of deliverable descriptions, rendered as a numbered
        list (``"D1: …"``, ``"D2: …"``, …).
    milestones
        Sequence of milestone dicts; each may have ``name``, ``date``,
        and ``payment`` keys. Rendered as a table.
    fees
        Free-text fee summary (e.g. ``"Fixed-price AUD 120,000 ex GST"``
        or ``"Time and materials at AUD 1,500 per day"``).
    governing_law
        Inherited from the parent MSA by default; same NSW default.

    Returns
    -------
    Document
        The freshly-built |Document|.

    Raises
    ------
    ValueError
        When neither ``parties`` nor ``client``/``vendor`` are supplied.

    .. warning::
        **Not legal advice.** See module docstring.

    .. versionadded:: 2026.05.29
    """
    if parties is None:
        if not client or not vendor:
            raise ValueError(
                "supply either 'parties' or both 'client' and 'vendor'"
            )
        parties = [{"name": client}, {"name": vendor}]
    _validate_parties(parties)

    document = Document()
    title = "Statement of Work"
    if project_name:
        title = f"Statement of Work — {project_name}"
    _add_title(document, title)
    _add_disclaimer(document)

    if effective_date:
        date_para = document.add_paragraph(
            f"Effective Date: {effective_date}"
        )
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    _add_parties_block(document, parties)

    # -- recital --
    parent_ref = (
        f"the Master Services Agreement \"{parent_msa}\""
        if parent_msa
        else "the Master Services Agreement entered into between the "
        "Parties (\"MSA\")"
    )
    document.add_paragraph(
        f"This Statement of Work (\"SOW\") is entered into under, and "
        f"is governed by the terms of, {parent_ref}. Capitalised terms "
        f"used and not defined here have the meanings given in the MSA. "
        f"In the event of conflict between this SOW and the MSA, the "
        f"MSA prevails unless this SOW expressly states otherwise."
    )

    # -- 1. Project Description --
    _add_clause(
        document,
        1,
        "Project Description",
        f"The Vendor will perform the services described in this SOW "
        f"for the Client in respect of "
        f"{project_name or 'the project described below'}.",
    )

    # -- 2. Deliverables --
    deliverables_paras: List[str] = []
    deliverables_paras.append(
        "The Vendor will deliver the following:"
    )
    if deliverables:
        for index, item in enumerate(deliverables, start=1):
            deliverables_paras.append(f"D{index}: {item}")
    else:
        deliverables_paras.append(
            "[Insert deliverable descriptions here.]"
        )
    _add_clause(document, 2, "Deliverables", deliverables_paras)

    # -- 3. Milestones --
    document.add_heading("3. Milestones and Schedule", level=1)
    if milestones:
        table = document.add_table(rows=1, cols=3)
        table.style = "Table Grid"
        header_cells = table.rows[0].cells
        header_cells[0].text = "Milestone"
        header_cells[1].text = "Target Date"
        header_cells[2].text = "Payment"
        for milestone in milestones:
            row = table.add_row().cells
            row[0].text = str(milestone.get("name", ""))
            row[1].text = str(milestone.get("date", ""))
            row[2].text = str(milestone.get("payment", ""))
    else:
        document.add_paragraph(
            "[Insert milestone schedule here.]"
        )

    # -- 4. Fees --
    fees_text = fees or (
        "[Insert fee structure here — fixed-price, time-and-materials, "
        "or capped time-and-materials. Reference the parent MSA's "
        "payment-terms clause.]"
    )
    _add_clause(
        document,
        4,
        "Fees",
        f"The fees payable for the services under this SOW are: "
        f"{fees_text} Invoices are payable in accordance with the "
        f"payment-terms clause of the MSA.",
    )

    # -- 5. Acceptance --
    _add_clause(
        document,
        5,
        "Acceptance Criteria",
        "Each deliverable will be deemed accepted on the earlier of: "
        "(a) the Client's written acceptance; or (b) the expiry of "
        "10 business days after delivery without the Client having "
        "given written notice of rejection identifying specific "
        "non-conformances with reasonable particularity.",
    )

    # -- 6. Assumptions and Dependencies --
    _add_clause(
        document,
        6,
        "Assumptions and Dependencies",
        "The fees and timeline assume that the Client will provide "
        "timely access to information, personnel, and decisions "
        "reasonably required by the Vendor. Material delays caused by "
        "the Client may give rise to a documented change request and "
        "an adjustment to the schedule and fees.",
    )

    # -- 7. Governing Law (inherited but restated) --
    _add_clause(
        document,
        7,
        "Governing Law",
        f"This SOW is governed by the laws of {governing_law} (as "
        f"specified in the MSA).",
    )

    document.add_page_break()
    _add_signature_block(document, parties)

    return document


# -- Contractor agreement -------------------------------------------------


def contractor_agreement(
    contractor: Optional[str] = None,
    engaging_party: Optional[str] = None,
    parties: Optional[Sequence[Mapping[str, str]]] = None,
    effective_date: Optional[str] = None,
    services_description: Optional[str] = None,
    day_rate: Optional[Union[int, float, str]] = None,
    currency: str = _DEFAULT_CURRENCY,
    payment_terms: str = _DEFAULT_PAYMENT_TERMS,
    term_months: Optional[int] = None,
    governing_law: str = _DEFAULT_GOVERNING_LAW,
) -> DocumentCls:
    """Build an Independent Contractor Agreement and return the |Document|.

    Generates a contractor (independent-services) agreement with the
    standard sections: services, fees, contractor status, IP, taxation
    and superannuation, confidentiality, termination, and governing law.
    The shape is biased toward the Australian Taxation Office's
    "independent contractor" tests — the document is *not* an
    employment contract and explicitly disclaims that characterisation.

    Parameters
    ----------
    contractor
        Convenience: the contractor's name. Pairs with ``engaging_party``.
    engaging_party
        Convenience: the engaging party's name.
    parties
        Explicit party sequence (overrides ``contractor`` /
        ``engaging_party``).
    effective_date
        ISO date string.
    services_description
        Free-text description of the services. ``None`` leaves a
        placeholder.
    day_rate
        Daily fee. Numeric values are rendered with thousand-separators
        and the ``currency`` symbol; strings are rendered verbatim
        (useful for non-trivial rate structures).
    currency
        ISO currency code; defaults to ``"AUD"``.
    payment_terms
        Net-X invoice terms; defaults to ``"Net 30"``.
    term_months
        Length of the engagement in months. ``None`` produces an
        open-ended term terminable on notice.
    governing_law
        Jurisdiction; defaults to ``"New South Wales, Australia"``.

    Returns
    -------
    Document
        The freshly-built |Document|.

    Raises
    ------
    ValueError
        When neither ``parties`` nor ``contractor``/``engaging_party``
        are supplied.

    .. warning::
        **Not legal advice.** See module docstring. Independent
        contractor / employee characterisation is fact-sensitive in
        Australia (Personnel Contracting / Jamsek; Fair Work Act 2009
        s15AA from August 2024) — have a lawyer confirm the
        characterisation fits the actual working relationship.

    .. versionadded:: 2026.05.29
    """
    if parties is None:
        if not contractor or not engaging_party:
            raise ValueError(
                "supply either 'parties' or both 'contractor' and "
                "'engaging_party'"
            )
        parties = [
            {"name": engaging_party},
            {"name": contractor},
        ]
    _validate_parties(parties)
    if term_months is not None and term_months <= 0:
        raise ValueError(
            "term_months must be > 0 or None; got %d" % term_months
        )

    if isinstance(day_rate, (int, float)):
        rate_text = f"{currency} {day_rate:,.2f} per day (ex GST)"
    elif isinstance(day_rate, str) and day_rate:
        rate_text = day_rate
    else:
        rate_text = "[Insert fee structure here.]"

    document = Document()
    _add_title(document, "Independent Contractor Agreement")
    _add_disclaimer(document)

    if effective_date:
        date_para = document.add_paragraph(
            f"Effective Date: {effective_date}"
        )
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    _add_parties_block(document, parties)
    document.add_paragraph(
        "The Engaging Party (Party 1) wishes to engage the Contractor "
        "(Party 2) to provide certain services on an independent "
        "contractor basis, and the Contractor wishes to provide those "
        "services on the terms below."
    )

    # -- 1. Services --
    services = services_description or (
        "[Insert a description of the services here. Be specific about "
        "scope, deliverables, and any service-level expectations.]"
    )
    _add_clause(
        document,
        1,
        "Services",
        f"The Contractor will provide the following services to the "
        f"Engaging Party: {services} The Contractor will perform the "
        f"services with due care and skill, in a professional manner, "
        f"and in accordance with applicable laws and any reasonable "
        f"directions provided by the Engaging Party as to the outcomes "
        f"required (but not the manner of work).",
    )

    # -- 2. Fees --
    _add_clause(
        document,
        2,
        "Fees and Invoicing",
        [
            f"The Contractor's fees are {rate_text}. Fees are exclusive "
            f"of GST. Where the Contractor is registered for GST, the "
            f"Contractor will issue a valid tax invoice and the "
            f"Engaging Party will pay the GST in addition to the fees.",
            f"The Contractor will invoice the Engaging Party monthly "
            f"in arrears. Invoices are payable {payment_terms} from the "
            f"date of a valid tax invoice.",
            "Reasonable out-of-pocket expenses pre-approved in writing "
            "by the Engaging Party are reimbursable on production of "
            "receipts.",
        ],
    )

    # -- 3. Independent Contractor Status --
    _add_clause(
        document,
        3,
        "Independent Contractor Status",
        [
            "The Contractor is engaged as an independent contractor "
            "and not as an employee, partner, agent, or joint venturer "
            "of the Engaging Party. Nothing in this Agreement creates "
            "an employment relationship.",
            "The Contractor is responsible for the manner and means by "
            "which the services are performed, supplies its own "
            "equipment (except as specifically provided by the "
            "Engaging Party), and may delegate or subcontract subject "
            "to the Engaging Party's prior written consent (not to be "
            "unreasonably withheld).",
            "The Contractor may provide services to other clients "
            "during the term, provided that doing so does not breach "
            "the confidentiality, conflict-of-interest, or "
            "non-solicitation clauses of this Agreement.",
        ],
    )

    # -- 4. Taxation, Superannuation, and Insurance --
    _add_clause(
        document,
        4,
        "Taxation, Superannuation, and Insurance",
        [
            "The Contractor is responsible for its own income tax, "
            "GST, and any other taxes payable in respect of the fees "
            "received under this Agreement. The Engaging Party will "
            "not deduct PAYG withholding from the Contractor's fees "
            "unless required to do so by law.",
            "Where the Contractor is an individual and the engagement "
            "is wholly or principally for the Contractor's labour, the "
            "Engaging Party may be required by the Superannuation "
            "Guarantee (Administration) Act 1992 (Cth) to make "
            "superannuation contributions on the Contractor's behalf. "
            "Where applicable, those contributions will be calculated "
            "on the labour component of the fees and remitted to the "
            "Contractor's nominated superannuation fund.",
            "The Contractor will maintain professional indemnity and "
            "public liability insurance reasonable for the services "
            "and provide certificates of currency on request.",
        ],
    )

    # -- 5. Intellectual Property --
    _add_clause(
        document,
        5,
        "Intellectual Property",
        [
            "Subject to payment of all fees due, the Contractor "
            "assigns to the Engaging Party all right, title, and "
            "interest in any intellectual property created by the "
            "Contractor in the performance of the services "
            "(\"Foreground IP\"), excluding any pre-existing "
            "intellectual property of the Contractor (\"Background "
            "IP\") or any third-party components.",
            "The Contractor grants the Engaging Party a perpetual, "
            "royalty-free, non-exclusive licence to use the "
            "Contractor's Background IP to the extent embedded in the "
            "Foreground IP and necessary for the Engaging Party to "
            "exploit the Foreground IP.",
            "The Contractor consents, to the maximum extent permitted "
            "by Part IX of the Copyright Act 1968 (Cth), to the "
            "Engaging Party performing acts that would otherwise "
            "infringe the Contractor's moral rights in the Foreground "
            "IP, provided such acts are reasonable in the context of "
            "the engagement.",
        ],
    )

    # -- 6. Confidentiality --
    _add_clause(
        document,
        6,
        "Confidentiality",
        "The Contractor will keep confidential all non-public "
        "information about the Engaging Party's business, customers, "
        "and operations learned in the course of the engagement, and "
        "will use that information solely to perform the services. "
        "These obligations survive termination of this Agreement for a "
        "period of three years.",
    )

    # -- 7. Term and Termination --
    if term_months is None:
        term_text = (
            "This Agreement commences on the Effective Date and "
            "continues until terminated. Either Party may terminate "
            "this Agreement for convenience on 14 days' written notice."
        )
    else:
        term_text = (
            f"This Agreement commences on the Effective Date and "
            f"continues for {term_months} month"
            f"{'s' if term_months != 1 else ''}, unless earlier "
            f"terminated. Either Party may terminate this Agreement "
            f"for convenience on 14 days' written notice."
        )
    _add_clause(
        document,
        7,
        "Term and Termination",
        [
            term_text,
            "Either Party may terminate this Agreement immediately by "
            "written notice if the other Party commits a material "
            "breach not remedied within 14 days of written notice, or "
            "becomes insolvent.",
            "On termination, the Contractor will deliver up all "
            "documents, materials, and Confidential Information of "
            "the Engaging Party in its possession.",
        ],
    )

    # -- 8. Liability --
    _add_clause(
        document,
        8,
        "Liability",
        [
            "Nothing in this Agreement excludes, restricts, or "
            "modifies any guarantee, right, or remedy implied by, or "
            "conferred under, the Australian Consumer Law or any other "
            "law that cannot lawfully be excluded.",
            "Subject to the preceding paragraph, and to the maximum "
            "extent permitted by law, the Contractor's total aggregate "
            "liability under or in connection with this Agreement is "
            "limited to the total fees paid by the Engaging Party in "
            "the 12 months preceding the event giving rise to the "
            "claim. Neither Party is liable for indirect or "
            "consequential loss.",
        ],
    )

    # -- 9. Governing Law --
    _add_clause(
        document,
        9,
        "Governing Law",
        f"This Agreement is governed by the laws of {governing_law}. "
        f"The Parties submit to the exclusive jurisdiction of the "
        f"courts of {governing_law}.",
    )

    document.add_page_break()
    _add_signature_block(document, parties)

    return document


__all__ = [
    "nda",
    "msa",
    "sow",
    "contractor_agreement",
]
