"""Legal industry template family — court paper / brief / declaration / TOA.

Closes #81.

This module exposes four template factories that build the legal-industry
document shapes lawyers, paralegals, and litigation-support staff produce
every day::

    from docx.kit.legal import (
        court_paper,
        table_of_authorities,
        brief,
        declaration,
    )

    doc = court_paper(
        court="Federal Court of Australia",
        division="New South Wales District Registry",
        case_no="NSD 1234 of 2026",
        parties=[
            {"role": "Plaintiff", "name": "Acme Corp Pty Ltd"},
            {"role": "Defendant", "name": "Beta Pty Ltd"},
        ],
        document_type="Statement of Claim",
        line_numbering=True,        # adds line numbers in left margin
        body=[
            {"heading": "Background",       "paragraphs": ["..."]},
            {"heading": "Cause of Action",  "paragraphs": ["..."]},
        ],
    )
    doc.save("statement-of-claim.docx")

The four factories — :func:`court_paper`, :func:`table_of_authorities`,
:func:`brief`, :func:`declaration` — are pure-Python compositions of the
existing python-docx public API: ``Document.add_heading``,
``Document.add_paragraph``, ``Document.add_table``,
``Section.set_line_numbering``, and ``Paragraph.add_table_of_authorities``.
The shapes follow common Australian / New South Wales litigation
practice (Federal Court of Australia formats, NSW Supreme Court
declaration-style affidavits, AGLC4 case-citation house style for the
Table of Authorities) so a small NSW litigation practice can use the
output as the *first draft* of a real filing without re-typing the
boilerplate every time.

.. warning::

    **Not legal advice.** Every document returned by this module is
    template boilerplate intended as a *starting point only*. The text
    has not been reviewed by a lawyer, makes assumptions about
    jurisdiction, court rules of formatting, party type, and procedural
    posture that may not fit a given matter, and elides clauses
    (verifications, prayers for relief, certificates of service,
    affidavit jurats sworn before a justice of the peace, …) that are
    commonly required by the rules of a specific court. Use the output
    as a structural skeleton only and have a lawyer review every word
    before filing.  The authors of python-docx accept no responsibility
    for losses arising from reliance on this boilerplate.

Common conventions across the four factories:

- **Heading block** — Court name, division / registry, case number, and
  parties block rendered at the top of the first page, matching the
  Federal Court of Australia / NSW Supreme Court "front sheet" layout.
- **Numbered paragraphs** — Body text is numbered (``"1."``, ``"2."``,
  …) so cross-references to "paragraph 3" remain stable as the draft
  evolves.  The numbering is rendered as plain text rather than
  ``w:numPr`` on purpose — court rules in many AUS jurisdictions
  require the paragraph numbers to survive a copy-paste into the
  judge's reasons.
- **Line numbering** — When ``line_numbering=True`` (court paper) or
  the equivalent flag on :func:`brief` / :func:`declaration`, the
  factory wires up Word's built-in line-numbering via
  :meth:`Section.set_line_numbering` (``w:sectPr/w:lnNumType``) so the
  numbers appear in the left margin in Word and Print Preview.  The
  default is ``count_by=1`` (every line) restarting on each new page,
  which matches Federal Court of Australia practice.
- **Signature block** — Last page carries a signature stub for the
  filing party (court paper / brief), or the declarant + witness
  (declaration), with name / title / date placeholders.
- **No XML reach-down** — The kit composes only public python-docx API
  (``Document.add_paragraph``, ``Document.add_heading``,
  ``Document.add_page_break``, ``Document.add_table``,
  ``Section.set_line_numbering``,
  ``Paragraph.add_table_of_authorities``).

.. versionadded:: 2026.05.29
"""

from __future__ import annotations

from typing import TYPE_CHECKING, List, Mapping, Optional, Sequence, Union

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

if TYPE_CHECKING:
    from docx.document import Document as DocumentCls
    from docx.text.paragraph import Paragraph


# -- Default values used across the four factories. NSW / AUS biased. --
_DEFAULT_COURT = "Federal Court of Australia"
_DEFAULT_DIVISION = "New South Wales District Registry"
_DEFAULT_AFFIRMED_AT = "Sydney"

# -- Standard "not legal advice" disclaimer rendered verbatim into every
# -- generated document so a downstream user opening the file in Word
# -- sees the same caveat the docstring above carries. --
_DISCLAIMER = (
    "DISCLAIMER: This document is template boilerplate generated by "
    "python-docx. It is not legal advice and has not been reviewed by "
    "a lawyer. Use as a starting point only and have qualified legal "
    "counsel review every word before filing or signing."
)


# -- Helpers --------------------------------------------------------------


def _add_disclaimer(document: DocumentCls) -> Paragraph:
    """Append the standard "not legal advice" notice to ``document``."""
    para = document.add_paragraph()
    run = para.add_run(_DISCLAIMER)
    run.italic = True
    run.bold = True
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    return para


def _add_centred(
    document: DocumentCls, text: str, style: str = "Normal", bold: bool = False
) -> Paragraph:
    """Append a centred paragraph using ``style`` (falling back to Normal)."""
    try:
        document.styles[style]
    except KeyError:
        style = "Normal"
    para = document.add_paragraph(style=style)
    run = para.add_run(text)
    if bold:
        run.bold = True
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    return para


def _enable_line_numbering(
    document: DocumentCls, spec: Union[bool, Mapping[str, int], None]
) -> None:
    """Apply Word's built-in line numbering to the document's first section.

    ``spec`` is a bool (True ⇒ defaults), a mapping of kwargs forwarded
    to :meth:`Section.set_line_numbering` (``count_by`` / ``start`` /
    ``distance`` / ``restart``), or |None| / False to leave the section
    untouched. The default uses ``count_by=1`` (every line is numbered)
    to match Federal Court of Australia / NSW Supreme Court practice.
    """
    if not spec:
        return
    section = document.sections[0]
    if spec is True:
        section.set_line_numbering(count_by=1)
    elif isinstance(spec, Mapping):
        section.set_line_numbering(**dict(spec))
    else:  # pragma: no cover - defensive
        raise TypeError(
            "line_numbering must be a bool or mapping; got %r"
            % type(spec).__name__
        )


def _add_court_heading_block(
    document: DocumentCls,
    court: str,
    division: Optional[str],
    case_no: Optional[str],
    parties: Sequence[Mapping[str, str]],
) -> List[Paragraph]:
    """Append the standard court-paper heading block.

    Renders the canonical Federal Court of Australia / NSW Supreme Court
    front-sheet layout::

        FEDERAL COURT OF AUSTRALIA
        New South Wales District Registry
        No. NSD 1234 of 2026

        BETWEEN:
            Acme Corp Pty Ltd                         Plaintiff
            Beta Pty Ltd                              Defendant
    """
    paragraphs: List[Paragraph] = []
    paragraphs.append(
        _add_centred(document, court.upper(), style="Title", bold=True)
    )
    if division:
        paragraphs.append(_add_centred(document, division, bold=True))
    if case_no:
        paragraphs.append(_add_centred(document, f"No. {case_no}"))
    paragraphs.append(document.add_paragraph(""))  # gap
    paragraphs.append(document.add_paragraph("BETWEEN:"))
    for party in parties:
        name = party.get("name", "").strip()
        role = party.get("role", "").strip()
        if not name:
            raise ValueError("each party requires a non-empty 'name'")
        # -- conventional layout: party name on the left, role flushed
        # -- right with a tab. We approximate with a single paragraph
        # -- containing both segments separated by a tab character so a
        # -- caller-supplied tab stop renders the role on the right. --
        text = f"\t{name}\t{role}" if role else f"\t{name}"
        paragraphs.append(document.add_paragraph(text))
    paragraphs.append(document.add_paragraph(""))  # gap
    return paragraphs


def _validate_parties(parties: Sequence[Mapping[str, str]]) -> None:
    """Raise :class:`ValueError` when ``parties`` is malformed.

    The expectation is a sequence of length >= 1 where every item is a
    mapping that includes a non-empty ``name``. A length-0 sequence is
    rejected because every court paper / brief identifies at least one
    party.
    """
    if not parties:
        raise ValueError("parties must contain at least one party")
    for index, party in enumerate(parties):
        if not isinstance(party, Mapping):  # type: ignore[arg-type]
            raise ValueError(
                "parties[%d] must be a mapping with a 'name' key" % index
            )
        if not party.get("name"):
            raise ValueError(
                "parties[%d] is missing a non-empty 'name'" % index
            )


def _add_numbered_section(
    document: DocumentCls,
    counter_start: int,
    section_spec: Mapping[str, object],
) -> int:
    """Render a ``{heading, paragraphs}`` body section, numbered.

    Returns the next paragraph number to use after this section. The
    numbering scheme is plain-text ("1.", "2.", …) so cross-references
    in counsel's reasons survive copy-paste between drafts.
    """
    heading = section_spec.get("heading")
    if heading:
        document.add_heading(str(heading), level=1)
    raw_paragraphs = section_spec.get("paragraphs", []) or []
    if isinstance(raw_paragraphs, str):
        raw_paragraphs = [raw_paragraphs]
    counter = counter_start
    for chunk in raw_paragraphs:
        if not chunk:
            continue
        document.add_paragraph(f"{counter}. {chunk}")
        counter += 1
    return counter


def _add_signature_block(
    document: DocumentCls,
    label: str,
    party_name: str,
) -> List[Paragraph]:
    """Append a signature stub: heading + Name / Title / Date placeholders."""
    paragraphs: List[Paragraph] = []
    paragraphs.append(document.add_heading(label, level=1))
    paragraphs.append(
        document.add_paragraph(f"Signed for and on behalf of {party_name}:")
    )
    paragraphs.append(
        document.add_paragraph("Name: ______________________________")
    )
    paragraphs.append(
        document.add_paragraph("Title: ______________________________")
    )
    paragraphs.append(
        document.add_paragraph("Date: ______________________________")
    )
    paragraphs.append(document.add_paragraph(""))  # gap
    return paragraphs


# -- court_paper ----------------------------------------------------------


def court_paper(
    court: str = _DEFAULT_COURT,
    division: Optional[str] = _DEFAULT_DIVISION,
    case_no: Optional[str] = None,
    parties: Optional[Sequence[Mapping[str, str]]] = None,
    document_type: str = "Court Paper",
    line_numbering: Union[bool, Mapping[str, int]] = False,
    body: Optional[Sequence[Mapping[str, object]]] = None,
) -> DocumentCls:
    """Build a court paper / pleading and return the |Document|.

    Generates a complete court-paper draft with the standard front-sheet
    layout (court name, division/registry, case number, parties block),
    the document type as a centred sub-title, and the supplied ``body``
    rendered as numbered paragraphs under their headings.  When
    ``line_numbering`` is truthy the document's first section is wired
    up with Word's built-in ``w:sectPr/w:lnNumType`` (i.e. real Word
    line-numbering rather than baked-in numerals in a separate column).

    Parameters
    ----------
    court
        Name of the court.  Rendered in the heading block in upper case.
        Defaults to ``"Federal Court of Australia"``.
    division
        Optional division / registry line under the court name (e.g.
        ``"New South Wales District Registry"``). |None| omits the line.
    case_no
        Court file / case number (e.g. ``"NSD 1234 of 2026"``).
        |None| omits the line; a placeholder is *not* inserted because
        many drafts genuinely don't yet have a number.
    parties
        Sequence of party dicts, each with ``name`` (required) and
        ``role`` (optional, e.g. ``"Plaintiff"`` / ``"Defendant"`` /
        ``"Applicant"`` / ``"Respondent"``).
    document_type
        Human-readable name of the pleading (e.g. ``"Statement of
        Claim"``, ``"Originating Application"``, ``"Notice of
        Motion"``).  Rendered as a centred sub-title.
    line_numbering
        ``True`` enables Word's built-in line numbering with
        ``count_by=1``.  A mapping is forwarded as kwargs to
        :meth:`Section.set_line_numbering` (``count_by`` / ``start`` /
        ``distance`` / ``restart``).  ``False`` (the default) leaves
        the section untouched.
    body
        Sequence of ``{heading, paragraphs}`` mappings.  Each section's
        heading is rendered as a Word ``Heading 1``; each paragraph is
        rendered as plain text prefixed with a running number ("1.",
        "2.", …) to match court-paper drafting convention.

    Returns
    -------
    Document
        The freshly-built |Document|.

    Raises
    ------
    ValueError
        When ``parties`` is missing or malformed.

    .. warning::
        **Not legal advice.** See the module docstring for the full
        disclaimer.  The output is starting-point boilerplate only.

    .. versionadded:: 2026.05.29
    """
    if parties is None:
        raise ValueError("parties is required")
    _validate_parties(parties)

    document = Document()
    _enable_line_numbering(document, line_numbering)

    _add_court_heading_block(document, court, division, case_no, parties)
    _add_centred(document, document_type, style="Subtitle", bold=True)
    _add_disclaimer(document)

    counter = 1
    if body:
        for section_spec in body:
            counter = _add_numbered_section(document, counter, section_spec)

    document.add_page_break()
    party_label = parties[0]["name"]
    _add_signature_block(document, "Filed by", party_label)

    return document


# -- table_of_authorities -------------------------------------------------


def table_of_authorities(
    citations: Optional[Sequence[Mapping[str, object]]] = None,
    title: str = "Table of Authorities",
    category: Optional[int] = None,
) -> DocumentCls:
    """Build a Table of Authorities document and return the |Document|.

    Renders the supplied citations as a numbered list under the
    ``Table of Authorities`` heading and appends a Word ``TOA`` complex
    field at the end of the document.  Word will replace the field with
    a live, page-aware Table of Authorities the first time the user
    presses ``F9`` or hits *Update Field*.  The text list above the
    field is the read-only fallback rendering the document falls back
    to in Word readers that don't refresh fields (Word for the web,
    LibreOffice's read-only mode, …).

    Parameters
    ----------
    citations
        Sequence of citation dicts.  Each may contain:

        * ``case`` (required) — full case citation in AGLC4 / Bluebook
          house style (e.g. ``"Donoghue v Stevenson [1932] AC 562"``).
        * ``first_pin`` (optional) — pinpoint paragraph or page where
          the case is first cited in the host brief.  Rendered after
          the citation as ``" at <pin>"``.
        * ``category`` (optional) — Word TOA category number (1 =
          Cases, 2 = Statutes, 3 = Other Authorities, …).  Reserved
          for future use; today rendered verbatim into the visible
          list but not yet split into category-specific TOA fields.
    title
        Heading text for the list.  Defaults to ``"Table of
        Authorities"``.
    category
        TOA ``\\c`` category switch.  ``None`` (the default) emits a
        TOA field without ``\\c`` so Word includes every category;
        pass an integer to filter (1 = Cases, 2 = Statutes, …).

    Returns
    -------
    Document
        The freshly-built |Document|.  The final paragraph holds the
        TOA complex field — calling :meth:`Document.update_fields` or
        opening the file in Word and pressing F9 refreshes the field
        from the live ``w:fldChar`` markup.

    Raises
    ------
    ValueError
        When any citation entry is missing the required ``case`` key.

    .. warning::
        **Not legal advice.** See the module docstring.

    .. versionadded:: 2026.05.29
    """
    document = Document()
    document.add_heading(title, level=1)
    _add_disclaimer(document)

    if citations:
        for index, item in enumerate(citations, start=1):
            if not isinstance(item, Mapping):  # type: ignore[arg-type]
                raise ValueError(
                    "citations[%d] must be a mapping with a 'case' key"
                    % (index - 1)
                )
            case_text = item.get("case")
            if not case_text:
                raise ValueError(
                    "citations[%d] is missing a non-empty 'case'"
                    % (index - 1)
                )
            pin = item.get("first_pin")
            display = (
                f"{case_text} at {pin}" if pin not in (None, "") else str(case_text)
            )
            document.add_paragraph(f"{index}. {display}")
    else:
        document.add_paragraph("[Insert citations here.]")

    # -- Append the live TOA complex field. The visible list above is
    # -- the readable fallback; Word will replace the field's cached
    # -- result with a fully-paginated Table of Authorities the first
    # -- time the user updates fields. --
    field_para = document.add_paragraph()
    field_para.add_table_of_authorities(category=category)

    return document


# -- brief ----------------------------------------------------------------


def brief(
    matter: Optional[str] = None,
    counsel: Optional[Mapping[str, str]] = None,
    instructing_solicitor: Optional[Mapping[str, str]] = None,
    court: str = _DEFAULT_COURT,
    division: Optional[str] = _DEFAULT_DIVISION,
    case_no: Optional[str] = None,
    parties: Optional[Sequence[Mapping[str, str]]] = None,
    line_numbering: Union[bool, Mapping[str, int]] = False,
    sections: Optional[Sequence[Mapping[str, object]]] = None,
    documents_index: Optional[Sequence[str]] = None,
) -> DocumentCls:
    """Build a barrister's brief and return the |Document|.

    Generates a "brief to counsel" cover document with the standard
    AUS-practice sections: brief title (matter name), counsel and
    instructing-solicitor blocks, observations / submissions sections
    rendered from ``sections``, and an index of enclosed documents.
    Suitable as the cover sheet on a litigation brief that bundles
    pleadings, witness statements, and authorities.

    Parameters
    ----------
    matter
        Human-readable matter name (e.g. ``"Smith v Jones"``).  Used as
        the document title.
    counsel
        Mapping with ``name`` (required) and optional ``chambers`` /
        ``email`` keys for the counsel briefed.
    instructing_solicitor
        Mapping with ``name`` and optional ``firm`` / ``email`` for the
        instructing solicitor.  |None| omits the block.
    court / division / case_no / parties
        Court-paper-style heading information; rendered when supplied.
        ``parties`` follows the :func:`court_paper` convention
        (``{name, role}`` mappings).
    line_numbering
        Same semantics as :func:`court_paper`.  Defaults to ``False``
        because briefs typically aren't filed and so don't need line
        numbers; pass ``True`` when the brief is destined for Court.
    sections
        Sequence of ``{heading, paragraphs}`` mappings rendered as
        numbered paragraphs (same shape as :func:`court_paper`).
    documents_index
        Optional sequence of document names.  Rendered as a numbered
        index at the end of the brief, before the signature block.

    Returns
    -------
    Document
        The freshly-built |Document|.

    Raises
    ------
    ValueError
        When ``matter`` is empty / missing, or when ``counsel`` lacks a
        non-empty ``name``.

    .. warning::
        **Not legal advice.** See the module docstring.

    .. versionadded:: 2026.05.29
    """
    if not matter:
        raise ValueError("matter is required")
    if not counsel or not counsel.get("name"):
        raise ValueError("counsel must be a mapping with a non-empty 'name'")
    if parties is not None:
        _validate_parties(parties)

    document = Document()
    _enable_line_numbering(document, line_numbering)

    _add_centred(document, "BRIEF TO COUNSEL", style="Title", bold=True)
    _add_centred(document, matter, style="Subtitle", bold=True)
    _add_disclaimer(document)

    if parties:
        _add_court_heading_block(document, court, division, case_no, parties)
    elif case_no:
        _add_centred(document, f"No. {case_no}")

    # -- Counsel block --
    document.add_heading("Counsel", level=1)
    counsel_name = counsel["name"]
    chambers = counsel.get("chambers")
    email = counsel.get("email")
    document.add_paragraph(counsel_name)
    if chambers:
        document.add_paragraph(chambers)
    if email:
        document.add_paragraph(email)

    # -- Instructing solicitor block --
    if instructing_solicitor:
        document.add_heading("Instructing Solicitor", level=1)
        sol_name = instructing_solicitor.get("name", "")
        sol_firm = instructing_solicitor.get("firm")
        sol_email = instructing_solicitor.get("email")
        if sol_name:
            document.add_paragraph(sol_name)
        if sol_firm:
            document.add_paragraph(sol_firm)
        if sol_email:
            document.add_paragraph(sol_email)

    # -- Numbered observations / submissions --
    counter = 1
    if sections:
        for section_spec in sections:
            counter = _add_numbered_section(document, counter, section_spec)

    # -- Enclosed-documents index --
    if documents_index:
        document.add_heading("Index of Documents", level=1)
        for index, name in enumerate(documents_index, start=1):
            if not name:
                continue
            document.add_paragraph(f"{index}. {name}")

    document.add_page_break()
    _add_signature_block(document, "Brief delivered by", "Instructing Solicitor")

    return document


# -- declaration ----------------------------------------------------------


def declaration(
    declarant: Optional[Mapping[str, str]] = None,
    affirmed_at: str = _DEFAULT_AFFIRMED_AT,
    affirmed_date: Optional[str] = None,
    paragraphs: Optional[Sequence[str]] = None,
    court: Optional[str] = None,
    division: Optional[str] = None,
    case_no: Optional[str] = None,
    parties: Optional[Sequence[Mapping[str, str]]] = None,
    line_numbering: Union[bool, Mapping[str, int]] = False,
) -> DocumentCls:
    """Build a witness declaration / affidavit and return the |Document|.

    Generates a NSW-style witness declaration: heading block (when
    court / parties supplied), declarant identification, numbered
    statements of fact, jurat (place + date), and signature stubs for
    declarant and witness.  The shape matches the Oaths Act 1900 (NSW)
    statutory declaration / affidavit conventions in common use across
    AUS state and federal courts.

    Parameters
    ----------
    declarant
        Mapping with ``name`` (required) and optional ``address`` /
        ``occupation`` keys identifying the deponent.
    affirmed_at
        Place where the declaration is affirmed / sworn (e.g.
        ``"Sydney"``).  Defaults to ``"Sydney"``.
    affirmed_date
        ISO date string rendered verbatim in the jurat.  ``None``
        leaves a placeholder underline so the witness can hand-write
        the date at signing time.
    paragraphs
        Sequence of statement-of-fact strings.  Each is rendered as a
        numbered paragraph ("1.", "2.", …) per witness-declaration
        drafting convention.
    court / division / case_no / parties
        Optional court-paper-style heading information.  When
        ``parties`` is supplied the declaration is treated as filed in
        a specific proceeding and the front sheet is included.
    line_numbering
        Same semantics as :func:`court_paper`.

    Returns
    -------
    Document
        The freshly-built |Document|.

    Raises
    ------
    ValueError
        When ``declarant`` is missing or lacks a non-empty ``name``.

    .. warning::
        **Not legal advice.** See the module docstring.

    .. versionadded:: 2026.05.29
    """
    if not declarant or not declarant.get("name"):
        raise ValueError(
            "declarant must be a mapping with a non-empty 'name'"
        )
    if parties is not None:
        _validate_parties(parties)

    document = Document()
    _enable_line_numbering(document, line_numbering)

    if parties:
        _add_court_heading_block(
            document, court or _DEFAULT_COURT, division, case_no, parties
        )

    _add_centred(document, "DECLARATION", style="Title", bold=True)
    _add_disclaimer(document)

    # -- Declarant identification --
    declarant_name = declarant["name"]
    parts: List[str] = [f"I, {declarant_name}"]
    occupation = declarant.get("occupation")
    if occupation:
        parts.append(f", {occupation}")
    address = declarant.get("address")
    if address:
        parts.append(f", of {address}")
    parts.append(", say as follows:")
    document.add_paragraph("".join(parts))

    # -- Numbered statements of fact --
    if paragraphs:
        for index, chunk in enumerate(paragraphs, start=1):
            if not chunk:
                continue
            document.add_paragraph(f"{index}. {chunk}")
    else:
        document.add_paragraph("[Insert numbered statements of fact here.]")

    # -- Jurat --
    document.add_paragraph("")
    jurat_date = affirmed_date or "______________________________"
    document.add_paragraph(
        f"Affirmed at {affirmed_at} on {jurat_date}."
    )

    # -- Signature stubs (declarant + witness) --
    document.add_paragraph("")
    document.add_paragraph(
        f"Declarant: ______________________________ ({declarant_name})"
    )
    document.add_paragraph("")
    document.add_paragraph(
        "Witness: ______________________________"
    )
    document.add_paragraph(
        "Witness Name: ______________________________"
    )
    document.add_paragraph(
        "Witness Qualification (JP / Solicitor / Notary): "
        "______________________________"
    )

    return document


__all__ = [
    "court_paper",
    "table_of_authorities",
    "brief",
    "declaration",
]
