"""Directly exposed API functions and classes, :func:`Document` for now.

Provides a syntactically more convenient API for interacting with the OpcPackage graph.
"""

from __future__ import annotations

import io
import os
from importlib import resources
from typing import IO, TYPE_CHECKING, cast

from docx.exceptions import NotAWordFileError, NotAWordTemplateError
from docx.opc.constants import CONTENT_TYPE as CT
from docx.package import Package

if TYPE_CHECKING:
    from docx.document import Document as DocumentObject
    from docx.parts.document import DocumentPart


#: Content types accepted as the main document part of a WordprocessingML package.
#: Includes the Transitional document/macro pair plus the template variants
#: (``.dotx`` / ``.dotm``). Closes upstream#1532, upstream#363,
#: upstream-PR#1537, upstream-PR#522, upstream-PR#523.
_WORD_CONTENT_TYPES = frozenset(
    (
        CT.WML_DOCUMENT_MAIN,
        CT.WML_DOCUMENT_MACRO,
        CT.WML_TEMPLATE_MAIN,
        CT.WML_TEMPLATE_MACRO,
    )
)


def Document(
    docx: "str | os.PathLike[str] | IO[bytes] | None" = None,
    recover: bool = False,
    huge_tree: bool = False,
    include_metadata: bool = True,
    password: str | None = None,
    strict: bool = False,
) -> DocumentObject:
    """Return a |Document| object loaded from `docx`, where `docx` can be a path to a
    ``.docx`` file (a ``str`` or :class:`os.PathLike`) or a file-like object.

    If `docx` is missing or ``None``, the built-in default document "template" is
    loaded. Both regular documents (``.docx`` / ``.docm``) and templates
    (``.dotx`` / ``.dotm``) are accepted; for templates the returned |Document|
    keeps the template content-type until the caller either saves as-is or
    uses :func:`Document.from_template` to derive a new document.

    .. versionchanged:: 2026.05.0
       Accepts :class:`os.PathLike` path arguments.

    When `recover` is True, XML parsing falls back to lxml's recovering parser for
    malformed parts (truncated, mismatched tags, invalid characters). Any parse
    warnings are collected on :attr:`Document.recovery_warnings`. Content that
    cannot be recovered is treated as empty. Irrecoverable failures unrelated to
    XML — for example, an invalid zip file or a password-protected document —
    continue to raise (:class:`PackageNotFoundError`, :class:`EncryptedDocumentError`).
    Default behaviour (``recover=False``) is unchanged.

    When `huge_tree` is True, lxml's ``huge_tree=True`` parser variant is used,
    lifting libxml2's default 10 MB-per-AttValue and 256-deep-nesting safety
    limits so extremely large documents can be parsed. Only enable for trusted
    input — the default parser's XML-bomb protections no longer apply. Closes
    upstream#1086.

    When `include_metadata` is False, both the core-properties part and the
    extended-properties part are cleared of all content at load time. This is
    useful for new documents (``docx`` omitted or |None|) where the bundled
    template's metadata (``Application``, ``AppVersion``, default
    ``lastModifiedBy``, ``Template`` name, etc.) should not be carried forward
    into documents generated by the caller. Defaults to True, preserving
    previous behaviour. Closes upstream#1464.

    When `password` is provided, an encrypted (password-protected) ``.docx``
    is decrypted before loading. This requires the optional
    ``python-ooxml-crypto`` dependency (install with
    ``pip install 'python-docx[encryption]'`` or
    ``pip install python-ooxml-crypto``). Opening an encrypted package without
    a password raises :class:`docx.exceptions.EncryptedDocumentError`.
    Opening a file wrapped in Azure RMS / AIP / IRM protection raises
    :class:`docx.exceptions.RmsProtectedDocumentError` — python-docx cannot
    decrypt RMS-protected files because the payload is keyed to the user's
    Microsoft 365 identity rather than a password.

    .. versionadded:: 2026.05.0
       The `huge_tree` and `include_metadata` parameters; ``.dotx`` / ``.dotm``
       templates now load directly; Strict-OOXML packages are transparently
       translated to Transitional on open; Flat-OPC (``<pkg:package>``) input
       is auto-detected.
    When `strict` is True, the package is flagged as ECMA-376 Strict
    conformance so :meth:`Document.is_strict` returns ``True`` and
    :meth:`Document.save(strict=None)` preserves the class. Strict
    packages are always auto-detected and translated to Transitional
    on open at the :class:`PackageReader` layer — ``strict=True`` is
    an explicit opt-in for ambiguous sniffs.

    .. versionadded:: 2026.05.10
       The `password` parameter.
    .. versionadded:: 2026.05.11
       The `strict` parameter.
    """
    if docx is None:
        docx = _default_docx_stream()
    elif isinstance(docx, os.PathLike):
        docx = os.fspath(docx)
    package = Package.open(
        docx, recover=recover, huge_tree=huge_tree, password=password,
        strict=strict,
    )
    document_part = cast("DocumentPart", package.main_document_part)
    if document_part.content_type not in _WORD_CONTENT_TYPES:
        raise NotAWordFileError(
            f"file '{docx}' is not a Word file, content type is "
            f"'{document_part.content_type}'",
            suggestion=(
                "Open .docx, .docm, .dotx, or .dotm files only. For .pptx /"
                " .xlsx use python-pptx / python-xlsx; the content type was "
                f"{document_part.content_type!r}."
            ),
            location=f"Document({docx!r})",
            operation="docx.Document",
        )
    document = document_part.document
    if not include_metadata:
        document.core_properties.clear_all()
        document.extended_properties.clear_all()
    return document


def from_template(template: str | IO[bytes]) -> DocumentObject:
    """Return a new |Document| derived from a ``.dotx`` / ``.dotm`` template.

    `template` is a path or file-like object for a template package. The
    returned |Document| has its main-document content-type switched to the
    regular (non-template) equivalent — ``.dotx`` → ``.docx`` and
    ``.dotm`` → ``.docm`` — so that :meth:`Document.save` produces a normal
    Word document rather than a template.

    Raises :class:`ValueError` if `template` is not a WordprocessingML
    template package.

    .. versionadded:: 2026.05.0
    """
    package = Package.open(template)
    document_part = cast("DocumentPart", package.main_document_part)
    source_ct = document_part.content_type
    if source_ct == CT.WML_TEMPLATE_MAIN:
        document_part.content_type = CT.WML_DOCUMENT_MAIN
    elif source_ct == CT.WML_TEMPLATE_MACRO:
        document_part.content_type = CT.WML_DOCUMENT_MACRO
    else:
        raise NotAWordTemplateError(
            f"file '{template}' is not a Word template, content type is "
            f"'{source_ct}'",
            suggestion=(
                "from_template() requires a .dotx or .dotm template package. "
                "Use Document() for a regular .docx / .docm document."
            ),
            location=f"from_template({template!r})",
            operation="docx.from_template",
        )
    return document_part.document


# -- expose `from_template` as `Document.from_template(...)` so the public
# -- API reads naturally regardless of whether callers grab it off the
# -- `docx` module or the `Document` factory. `Document` is a function
# -- (not a class), so plain attribute assignment gives the right callable.
Document.from_template = from_template  # type: ignore[attr-defined]


# -- expose `repair` as `Document.repair(...)`. Imported lazily to avoid a
# -- circular import: `docx.repair` ultimately calls back into this module's
# -- `Document(...)` factory through ``docx.api.Document``. --
def _repair(  # noqa: D401 -- attribute, not a top-level function
    docx_arg: "str | os.PathLike[str] | IO[bytes]",
    strategy: str = "best-effort",
):
    """Best-effort recovery loader. See :func:`docx.repair.repair` for full docs.

    Returns a ``(Document, RepairReport)`` tuple.

    .. versionadded:: 2026.05.13
    """
    from docx.repair import repair as _repair_impl

    return _repair_impl(docx_arg, strategy=strategy)


Document.repair = _repair  # type: ignore[attr-defined]


# -- expose ``stream`` as ``Document.stream(...)``. The streaming reader is
# -- a separate type (``StreamingDocument``) with a strictly read-only
# -- contract — see :mod:`docx.streaming` for the full decision tree. --
def _stream(
    source: "str | os.PathLike[str] | IO[bytes] | bytes",
):
    """Bounded-memory read-only loader. See :class:`docx.streaming.StreamingDocument`.

    Returns a :class:`StreamingDocument` usable as a context manager. The
    body of ``word/document.xml`` is iterated via ``lxml.iterparse`` and
    paragraphs / tables are released as soon as the consumer has yielded,
    so peak memory stays bounded even for multi-GB documents::

        with Document.stream("big.docx") as doc:
            for para in doc.paragraphs:
                if para.style.name == "Heading 1":
                    print(para.text)

    .. versionadded:: 2026.05.13
    """
    from docx.streaming import StreamingDocument

    return StreamingDocument(source)


Document.stream = _stream  # type: ignore[attr-defined]


# -- expose `from_html` / `from_html_string` as `Document.from_html(...)` and
# -- `Document.from_html_string(...)`. The HTML importer lives in
# -- `docx.html_import` and is the read-side companion to
# -- `docx.html_export.document_to_html` (`Document.to_html()`). LaTeX
# -- import is intentionally out of scope for this module — the Math /
# -- equation authoring API in `docx.math` is the lower-level lever a
# -- future LaTeX importer would build on top of. --
def _from_html(  # noqa: D401 -- attribute, not a top-level function
    source: "str | os.PathLike[str] | IO[bytes] | IO[str]",
    clean: bool = True,
) -> "DocumentObject":
    """Build a |Document| from an HTML file or stream.

    See :func:`docx.html_import.from_html` for the full contract.

    Element mapping (preview-grade):

    * ``<h1>`` … ``<h6>``     → ``Heading 1`` … ``Heading 6``
    * ``<p>``                 → body paragraph
    * ``<strong>`` / ``<b>``  → bold runs
    * ``<em>`` / ``<i>``      → italic runs
    * ``<u>``                 → underlined runs
    * ``<a href>``            → hyperlinks (``http`` / ``https`` /
                                ``mailto`` only)
    * ``<ul>`` / ``<ol>``     → ``List Bullet`` / ``List Number`` items
    * ``<table>``             → Word table
    * ``<img>``               → embedded picture (``data:`` URLs only;
                                remote URLs degrade to alt-text)
    * ``<blockquote>``        → ``Quote`` style paragraph
    * ``<code>`` / ``<pre>``  → monospace runs / paragraphs

    With ``clean=True`` (the default) ``<script>``, ``<style>``, and
    HTML comments are stripped, and ``class`` / ``id`` attributes are
    dropped. ``style`` attributes are honoured only for ``color``
    (best-effort).

    LaTeX import is **not** supported by this method; future-work
    candidate. Use :class:`docx.math.OMath` to author equations
    programmatically today.

    .. versionadded:: 2026.05.14
    """
    from docx.html_import import from_html as _from_html_impl

    return _from_html_impl(source, clean=clean)


def _from_html_string(html_text: str, clean: bool = True) -> "DocumentObject":
    """Build a |Document| from an HTML string.

    See :func:`docx.html_import.from_html_string` for the full contract.

    .. versionadded:: 2026.05.14
    """
    from docx.html_import import from_html_string as _impl

    return _impl(html_text, clean=clean)


Document.from_html = _from_html  # type: ignore[attr-defined]
Document.from_html_string = _from_html_string  # type: ignore[attr-defined]


def _default_docx_stream() -> io.BytesIO:
    """Return a `BytesIO` of the built-in default .docx package.

    Uses :mod:`importlib.resources` so the template is located correctly when
    `docx` is imported from a zip/egg, a PyInstaller/cx_freeze bundle, or any
    other non-filesystem :class:`importlib.abc.Traversable`. Closes upstream#176,
    upstream-PR#1310, upstream-PR#177.
    """
    template = resources.files("docx").joinpath("templates/default.docx")
    return io.BytesIO(template.read_bytes())
