"""Directly exposed API functions and classes, :func:`Document` for now.

Provides a syntactically more convenient API for interacting with the OpcPackage graph.
"""

from __future__ import annotations

import io
import os
from importlib import resources
from typing import IO, TYPE_CHECKING, cast

from docx.opc.constants import CONTENT_TYPE as CT
from docx.package import Package

if TYPE_CHECKING:
    from docx.document import Document as DocumentObject
    from docx.parts.document import DocumentPart


def Document(
    docx: "str | os.PathLike[str] | IO[bytes] | None" = None,
    recover: bool = False,
    huge_tree: bool = False,
    include_metadata: bool = True,
) -> DocumentObject:
    """Return a |Document| object loaded from `docx`, where `docx` can be a path to a
    ``.docx`` file (a ``str`` or :class:`os.PathLike`) or a file-like object.

    If `docx` is missing or ``None``, the built-in default document "template" is
    loaded.

    .. versionchanged:: 1.3.0.dev0
       Accepts :class:`os.PathLike` path arguments.

    When `recover` is True, XML parsing falls back to lxml's recovering parser for
    malformed parts (truncated, mismatched tags, invalid characters). Any parse
    warnings are collected on :attr:`Document.recovery_warnings`. Content that
    cannot be recovered is treated as empty. Irrecoverable failures unrelated to
    XML — for example, an invalid zip file or a password-protected document —
    continue to raise (:class:`PackageNotFoundError`, :class:`EncryptedDocumentError`).
    Default behaviour (``recover=False``) is unchanged.

    When `huge_tree` is True, lxml's ``huge_tree=True`` parser variant is used,
    lifting libxml2's default 10 MB-per-AttValue and 256-deep-nesting safety
    limits so extremely large documents can be parsed. Only enable for trusted
    input — the default parser's XML-bomb protections no longer apply. Closes
    upstream#1086.

    When `include_metadata` is False, both the core-properties part and the
    extended-properties part are cleared of all content at load time. This is
    useful for new documents (``docx`` omitted or |None|) where the bundled
    template's metadata (``Application``, ``AppVersion``, default
    ``lastModifiedBy``, ``Template`` name, etc.) should not be carried forward
    into documents generated by the caller. Defaults to True, preserving
    previous behaviour. Closes upstream#1464.

    .. versionadded:: 1.3.0.dev0
       The `huge_tree` and `include_metadata` parameters.
    """
    if docx is None:
        docx = _default_docx_stream()
    elif isinstance(docx, os.PathLike):
        docx = os.fspath(docx)
    package = Package.open(docx, recover=recover, huge_tree=huge_tree)
    document_part = cast("DocumentPart", package.main_document_part)
    if document_part.content_type not in (CT.WML_DOCUMENT_MAIN, CT.WML_DOCUMENT_MACRO):
        raise ValueError(
            f"file '{docx}' is not a Word file, content type is '{document_part.content_type}'"
        )
    document = document_part.document
    if not include_metadata:
        document.core_properties.clear_all()
        document.extended_properties.clear_all()
    return document


def _default_docx_stream() -> io.BytesIO:
    """Return a `BytesIO` of the built-in default .docx package.

    Uses :mod:`importlib.resources` so the template is located correctly when
    `docx` is imported from a zip/egg, a PyInstaller/cx_freeze bundle, or any
    other non-filesystem :class:`importlib.abc.Traversable`. Closes upstream#176,
    upstream-PR#1310, upstream-PR#177.
    """
    template = resources.files("docx").joinpath("templates/default.docx")
    return io.BytesIO(template.read_bytes())
