# -*- coding: utf-8 -*-
#
# python-docx documentation build configuration file, created by
# sphinx-quickstart on Sat Jun 29 17:34:36 2013.
#
# This file is execfile()d with the current directory set to its containing
# dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath(".."))

from docx import __version__  # noqa


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

# -- Napoleon (Google / NumPy docstring support) ----------------------------
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True


def setup(app):
    r"""Install a pre-napoleon hook that disables napoleon's attribute-style
    parsing for property/attribute/data docstrings.

    ----------------------------------------------------------------------
    Why this hook exists
    ----------------------------------------------------------------------
    This fork's public API is heavily documented in RST style. Property and
    attribute docstrings frequently quote OOXML element / attribute names
    using single-backtick inline code — e.g.::

        Read/write. Corresponds to the `w:moveFrom` element on this run.

    Sphinx-napoleon's ``_parse_attribute_docstring`` path treats concise
    attribute docstrings as ``"type : description"`` and splits on the
    first colon it finds. Because ``w:moveFrom`` contains a colon *inside*
    a backtick span, napoleon misinterprets ``w:moveFrom`` as the
    ``:type:`` field, producing ~42 bogus ``docutils`` warnings of the
    form "Unknown target name: 'w:moveFrom'" (and similar) across
    ``chart.py``, ``content_controls.py``, ``document.py``,
    ``permissions.py``, ``ruby.py``, ``section.py``, ``styles/style.py``,
    ``table.py``, ``text/paragraph.py``, ``text/run.py``, and
    ``tracked_changes.py``.

    ----------------------------------------------------------------------
    How it works
    ----------------------------------------------------------------------
    We register two ``autodoc-process-docstring`` listeners around
    napoleon's own listener (which sits at the default priority of 500):

      * ``_snapshot`` runs at priority 100 — before napoleon — and takes a
        copy of the raw docstring lines for every ``property``/
        ``attribute``/``data`` object.
      * ``_restore`` runs at priority 900 — after napoleon has mangled
        the lines — and writes the pristine snapshot back in place,
        undoing the ``type : description`` split.

    The net effect is: napoleon is a no-op for attribute-style docstrings
    (which are already valid RST), and still parses Google/NumPy
    method/function/class docstrings normally.

    ----------------------------------------------------------------------
    Do not remove without fixing the root cause
    ----------------------------------------------------------------------
    The alternative is to rewrite every single-backtick OOXML reference
    in those ~11 files to use double-backtick literals (``w:moveFrom``),
    so the napoleon ``:``-split never triggers. That's a large mechanical
    refactor for a purely cosmetic docs-parsing issue that this hook
    already handles cleanly. If you remove this hook, run
    ``cd docs && python -m sphinx -b html . _build/html`` and confirm the
    build is still warning-free first.
    """
    snapshots: dict = {}

    def _snapshot(app, what, name, obj, options, lines):
        if what in ("property", "attribute", "data"):
            snapshots[name] = list(lines)

    def _restore(app, what, name, obj, options, lines):
        if what in ("property", "attribute", "data") and name in snapshots:
            lines[:] = snapshots.pop(name)

    # Napoleon's listener registers at default priority (500). Use 100 for
    # snapshot (runs first) and 900 for restore (runs last).
    app.connect("autodoc-process-docstring", _snapshot, priority=100)
    app.connect("autodoc-process-docstring", _restore, priority=900)


# Add any paths that contain templates here, relative to this directory.
# templates_path = ["_templates"]

# The suffix of source filenames.
source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "python-docx"
copyright = "2013, Steve Canny"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = __version__
# The full version, including alpha/beta/rc tags.
release = __version__

# A string of reStructuredText that will be included at the end of every source
# file that is read. This is the right place to add substitutions that should
# be available in every file.
rst_epilog = """
.. |api-Document| replace:: :class:`docx.api.Document`

.. |AttributeError| replace:: :exc:`.AttributeError`

.. |BaseStyle| replace:: :class:`.BaseStyle`

.. |BlockItemContainer| replace:: :class:`.BlockItemContainer`

.. |_Body| replace:: :class:`._Body`

.. |Bookmark| replace:: :class:`.Bookmark`

.. |Bookmarks| replace:: :class:`.Bookmarks`

.. |Border| replace:: :class:`.Border`

.. |BuildingBlock| replace:: :class:`.BuildingBlock`

.. |BuildingBlockCategory| replace:: :class:`.BuildingBlockCategory`

.. |_Cell| replace:: :class:`._Cell`

.. |CellBorders| replace:: :class:`.CellBorders`

.. |CellMargins| replace:: :class:`.CellMargins`

.. |CellShading| replace:: :class:`.CellShading`

.. |_CharacterStyle| replace:: :class:`.CharacterStyle`

.. |CharacterStyle| replace:: :class:`.CharacterStyle`

.. |Chart| replace:: :class:`.Chart`

.. |Cm| replace:: :class:`.Cm`

.. |ColorFormat| replace:: :class:`.ColorFormat`

.. |Column| replace:: :class:`.Column`

.. |_Column| replace:: :class:`._Column`

.. |_Columns| replace:: :class:`._Columns`

.. |Comment| replace:: :class:`.Comment`

.. |Comments| replace:: :class:`.Comments`

.. |CompatFlags| replace:: :class:`.CompatFlags`

.. |CompatSettings| replace:: :class:`.CompatSettings`

.. |ContentControl| replace:: :class:`.ContentControl`

.. |DataBinding| replace:: :class:`.DataBinding`

.. |DocumentProtection| replace:: :class:`.DocumentProtection`

.. |CoreProperties| replace:: :class:`.CoreProperties`

.. |CustomProperties| replace:: :class:`.CustomProperties`

.. |CustomXmlPart| replace:: :class:`.CustomXmlPart`

.. |datetime| replace:: :class:`.datetime.datetime`

.. |Document| replace:: :class:`.Document`

.. |DocumentGrid| replace:: :class:`.DocumentGrid`

.. |DocumentPart| replace:: :class:`.DocumentPart`

.. |DocumentStatistics| replace:: :class:`.DocumentStatistics`

.. |docx| replace:: ``python-docx``

.. |Drawing| replace:: :class:`.Drawing`

.. |EastAsianLayout| replace:: :class:`.EastAsianLayout`

.. |EmbeddedObject| replace:: :class:`.EmbeddedObject`

.. |EndnoteProperties| replace:: :class:`.EndnoteProperties`

.. |Endnote| replace:: :class:`.Endnote`

.. |Endnotes| replace:: :class:`.Endnotes`

.. |Emu| replace:: :class:`.Emu`

.. |Equation| replace:: :class:`.Equation`

.. |False| replace:: :class:`False`

.. |Field| replace:: :class:`.Field`

.. |float| replace:: :class:`.float`

.. |FloatingImage| replace:: :class:`.FloatingImage`

.. |Font| replace:: :class:`.Font`

.. |FontTable| replace:: :class:`.FontTable`

.. |_Footer| replace:: :class:`._Footer`

.. |FooterPart| replace:: :class:`.FooterPart`

.. |FootnoteProperties| replace:: :class:`.FootnoteProperties`

.. |Footnote| replace:: :class:`.Footnote`

.. |Footnotes| replace:: :class:`.Footnotes`

.. |FormattingChange| replace:: :class:`.FormattingChange`

.. |FormField| replace:: :class:`.FormField`

.. |Glossary| replace:: :class:`.Glossary`

.. |_Header| replace:: :class:`._Header`

.. |HeaderPart| replace:: :class:`.HeaderPart`

.. |HeadingIssue| replace:: :class:`.HeadingIssue`

.. |Hyperlink| replace:: :class:`.Hyperlink`

.. |ImageParts| replace:: :class:`.ImageParts`

.. |Inches| replace:: :class:`.Inches`

.. |InkAnnotation| replace:: :class:`.InkAnnotation`

.. |InlineShape| replace:: :class:`.InlineShape`

.. |InlineShapes| replace:: :class:`.InlineShapes`

.. |InvalidSpanError| replace:: :class:`.InvalidSpanError`

.. |int| replace:: :class:`.int`

.. |KeyError| replace:: :exc:`.KeyError`

.. |_LatentStyle| replace:: :class:`._LatentStyle`

.. |LatentStyles| replace:: :class:`.LatentStyles`

.. |Length| replace:: :class:`.Length`

.. |Level| replace:: :class:`.Level`

.. |LineNumbering| replace:: :class:`.LineNumbering`

.. |MailMerge| replace:: :class:`.MailMerge`

.. |MoveRevision| replace:: :class:`.MoveRevision`

.. |None| replace:: :class:`.None`

.. |Numbering| replace:: :class:`.Numbering`

.. |NumberingDefinition| replace:: :class:`.NumberingDefinition`

.. |NumberingPart| replace:: :class:`.NumberingPart`

.. |_NumberingStyle| replace:: :class:`._NumberingStyle`

.. |OpcPackage| replace:: :class:`.OpcPackage`

.. |PageBorder| replace:: :class:`.PageBorder`

.. |PageBorders| replace:: :class:`.PageBorders`

.. |Paragraph| replace:: :class:`.Paragraph`

.. |ParagraphBorders| replace:: :class:`.ParagraphBorders`

.. |ParagraphFormat| replace:: :class:`.ParagraphFormat`

.. |_ParagraphStyle| replace:: :class:`.ParagraphStyle`

.. |ParagraphStyle| replace:: :class:`.ParagraphStyle`

.. |Part| replace:: :class:`.Part`

.. |PermissionRange| replace:: :class:`.PermissionRange`

.. |Pt| replace:: :class:`.Pt`

.. |_Relationship| replace:: :class:`._Relationship`

.. |Relationships| replace:: :class:`._Relationships`

.. |RenderedPageBreak| replace:: :class:`.RenderedPageBreak`

.. |RGBColor| replace:: :class:`.RGBColor`

.. |_Row| replace:: :class:`._Row`

.. |_Rows| replace:: :class:`._Rows`

.. |RubyAnnotation| replace:: :class:`.RubyAnnotation`

.. |Run| replace:: :class:`.Run`

.. |SearchMatch| replace:: :class:`.SearchMatch`

.. |Section| replace:: :class:`.Section`

.. |SectionColumns| replace:: :class:`.SectionColumns`

.. |Sections| replace:: :class:`.Sections`

.. |Settings| replace:: :class:`.Settings`

.. |SignatureInfo| replace:: :class:`.SignatureInfo`

.. |SmartArt| replace:: :class:`.SmartArt`

.. |str| replace:: :class:`.str`

.. |Styles| replace:: :class:`.Styles`

.. |StylesPart| replace:: :class:`.StylesPart`

.. |Symbol| replace:: :class:`.Symbol`

.. |Table| replace:: :class:`.Table`

.. |TableBorders| replace:: :class:`.TableBorders`

.. |TableStyleFlags| replace:: :class:`.TableStyleFlags`

.. |_TableStyle| replace:: :class:`._TableStyle`

.. |TabStop| replace:: :class:`.TabStop`

.. |TabStops| replace:: :class:`.TabStops`

.. |_Text| replace:: :class:`._Text`

.. |TextFrame| replace:: :class:`.TextFrame`

.. |Theme| replace:: :class:`.Theme`

.. |ThemeColors| replace:: :class:`.ThemeColors`

.. |ThemeFonts| replace:: :class:`.ThemeFonts`

.. |TrackedChange| replace:: :class:`.TrackedChange`

.. |True| replace:: :class:`True`

.. |ValueError| replace:: :class:`ValueError`

.. |Watermark| replace:: :class:`.Watermark`

.. |WD_ANCHOR_H| replace:: :class:`.WD_ANCHOR_H`

.. |WD_ANCHOR_V| replace:: :class:`.WD_ANCHOR_V`

.. |WD_BORDER_STYLE| replace:: :class:`.WD_BORDER_STYLE`

.. |WD_BUILDING_BLOCK_GALLERY| replace:: :class:`.WD_BUILDING_BLOCK_GALLERY`

.. |WD_DOC_GRID_TYPE| replace:: :class:`.WD_DOC_GRID_TYPE`

.. |WD_LINE_NUMBERING_RESTART| replace:: :class:`.WD_LINE_NUMBERING_RESTART`

.. |WD_PROTECTION| replace:: :class:`.WD_PROTECTION`

.. |WD_SHADING_PATTERN| replace:: :class:`.WD_SHADING_PATTERN`

.. |WD_TABLE_AUTOFIT| replace:: :class:`.WD_TABLE_AUTOFIT`

.. |WD_VIEW| replace:: :class:`.WD_VIEW`

.. |WD_WRAP_TYPE| replace:: :class:`.WD_WRAP_TYPE`

.. |WebSettings| replace:: :class:`.WebSettings`
"""


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build"]

# -- Autodoc -----------------------------------------------------------------

# Default options applied to every ``.. autoclass::`` / ``.. automodule::``
# directive. Individual directives can still override these with their own
# option list.
autodoc_default_options = {
    "members": True,
    "show-inheritance": True,
}

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []


# -- Options for HTML output ------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "furo"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "source_repository": "https://github.com/loadfix/python-docx/",
    "source_branch": "master",
    "source_directory": "docs/",
}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# Furo supplies its own sidebar out of the box; keep defaults.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = "python-docxdoc"


# -- Options for LaTeX output -----------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file,
#  target name,
#  title,
#  author,
#  documentclass [howto/manual]).
latex_documents = [
    ("index", "python-docx.tex", "python-docx Documentation", "Steve Canny", "manual"),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output -----------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [("index", "python-docx", "python-docx Documentation", ["Steve Canny"], 1)]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output ---------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        "index",
        "python-docx",
        "python-docx Documentation",
        "Steve Canny",
        "python-docx",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {"python": ("https://docs.python.org/3/", None)}
