"""Custom element classes for Office Math Markup Language (OMML).

OMML is Word's native equation format, stored inline using the ``m:`` namespace
(``http://schemas.openxmlformats.org/officeDocument/2006/math``), either as
``m:oMath`` (inline) or ``m:oMathPara`` (display-mode paragraph).

The element classes themselves live in the shared ``ooxml_math`` package —
this module is a thin re-export kept in place so that legacy imports
(``from docx.oxml.math import CT_OMath``) continue to work unchanged. The
shared package was extracted to give ``python-pptx`` equal access to OMML
authoring without copy-pasting the classes, and to make future OMML growth
(the operator tree, accents, fractions, radicals, ...) a single code change
rather than a per-parent fork.

As of ``ooxml_math`` 0.2.0 the full OMML operator tree from
``shared-math.xsd`` is modelled: fractions, radicals, delimiters, matrices,
n-ary operators, sub/superscripts, limits & functions, boxes & phantoms,
grouping characters, accents & bars, equation arrays, plus every ``*Pr``
companion and the paragraph / document-level property blocks. Each
``CT_*`` class is re-exported verbatim so downstream ``from docx.oxml.math
import CT_F`` etc. resolve without callers having to learn the shared
package name.
"""

from __future__ import annotations

from ooxml_math.oxml import (
    CT_Acc,
    CT_AccPr,
    CT_Bar,
    CT_BarPr,
    CT_BorderBox,
    CT_BorderBoxPr,
    CT_Box,
    CT_BoxPr,
    CT_BreakBin,
    CT_BreakBinSub,
    CT_Char,
    CT_CtrlPr,
    CT_D,
    CT_DPr,
    CT_EqArr,
    CT_EqArrPr,
    CT_F,
    CT_FPr,
    CT_FType,
    CT_Func,
    CT_FuncPr,
    CT_GroupChr,
    CT_GroupChrPr,
    CT_Integer2,
    CT_Integer255,
    CT_LimLoc,
    CT_LimLow,
    CT_LimLowPr,
    CT_LimUpp,
    CT_LimUppPr,
    CT_M,
    CT_ManualBreak,
    CT_MathPr,
    CT_MathR,
    CT_MathT,
    CT_MC,
    CT_MCPr,
    CT_MCS,
    CT_MPr,
    CT_MR,
    CT_Nary,
    CT_NaryPr,
    CT_OMath,
    CT_OMathArg,
    CT_OMathArgPr,
    CT_OMathJc,
    CT_OMathPara,
    CT_OMathParaPr,
    CT_OnOff,
    CT_Phant,
    CT_PhantPr,
    CT_PhantProps,
    CT_Rad,
    CT_RadPr,
    CT_RPR,
    CT_Script,
    CT_Shp,
    CT_SpacingRule,
    CT_SPre,
    CT_SPrePr,
    CT_SSub,
    CT_SSubPr,
    CT_SSubSup,
    CT_SSubSupPr,
    CT_SSup,
    CT_SSupPr,
    CT_String,
    CT_Style,
    CT_Sub,
    CT_Sup,
    CT_Text,
    CT_TopBot,
    CT_TwipsMeasure,
    CT_UnSignedInteger,
    CT_XAlign,
    CT_YAlign,
)

__all__ = [
    # -- 0.1.0 envelope --------------------------------------------------
    "CT_MathR",
    "CT_MathT",
    "CT_OMath",
    "CT_OMathPara",
    # -- 0.2.0 operator tree (containers) --------------------------------
    "CT_Acc",
    "CT_Bar",
    "CT_BorderBox",
    "CT_Box",
    "CT_D",
    "CT_EqArr",
    "CT_F",
    "CT_Func",
    "CT_GroupChr",
    "CT_LimLow",
    "CT_LimUpp",
    "CT_M",
    "CT_MC",
    "CT_MR",
    "CT_Nary",
    "CT_Phant",
    "CT_Rad",
    "CT_SPre",
    "CT_SSub",
    "CT_SSubSup",
    "CT_SSup",
    "CT_Sub",
    "CT_Sup",
    # -- 0.2.0 *Pr property blocks ---------------------------------------
    "CT_AccPr",
    "CT_BarPr",
    "CT_BorderBoxPr",
    "CT_BoxPr",
    "CT_DPr",
    "CT_EqArrPr",
    "CT_FPr",
    "CT_FuncPr",
    "CT_GroupChrPr",
    "CT_LimLowPr",
    "CT_LimUppPr",
    "CT_MathPr",
    "CT_MCPr",
    "CT_MPr",
    "CT_NaryPr",
    "CT_OMathArgPr",
    "CT_OMathParaPr",
    "CT_PhantPr",
    "CT_PhantProps",
    "CT_RadPr",
    "CT_SPrePr",
    "CT_SSubPr",
    "CT_SSubSupPr",
    "CT_SSupPr",
    # -- 0.2.0 shared wrappers + simple-value leaves ---------------------
    "CT_BreakBin",
    "CT_BreakBinSub",
    "CT_Char",
    "CT_CtrlPr",
    "CT_FType",
    "CT_Integer2",
    "CT_Integer255",
    "CT_LimLoc",
    "CT_ManualBreak",
    "CT_MCS",
    "CT_OMathArg",
    "CT_OMathJc",
    "CT_OnOff",
    "CT_RPR",
    "CT_Script",
    "CT_Shp",
    "CT_SpacingRule",
    "CT_String",
    "CT_Style",
    "CT_Text",
    "CT_TopBot",
    "CT_TwipsMeasure",
    "CT_UnSignedInteger",
    "CT_XAlign",
    "CT_YAlign",
]
